#!/bin/bash
# Index generator — builds INDEX.md from knowledge base files

KNOWLEDGE_BASE_DIR="${COMPANY_DOCS_HOME:-.}/knowledge-base"

rebuild_index() {
    local index_file="$KNOWLEDGE_BASE_DIR/INDEX.md"
    local now
    now=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date +"%Y-%m-%d")

    # Collect all docs grouped by category
    declare -A category_docs

    while IFS= read -r file; do
        [ "$file" = "$index_file" ] && continue

        local rel_path="${file#$KNOWLEDGE_BASE_DIR/}"
        local title
        title=$(sed -n 's/^title: *"\(.*\)"/\1/p' "$file" | head -1)
        local category
        category=$(sed -n 's/^category: *\(.*\)$/\1/p' "$file" | head -1)
        local tags
        tags=$(sed -n 's/^tags: *\(.*\)$/\1/p' "$file" | head -1)

        [ -z "$title" ] && title="$rel_path"
        [ -z "$category" ] && category="uncategorized"

        local entry="- [${title}](${rel_path}) — tags: ${tags:-none}"
        category_docs["$category"]+="${entry}"$'\n'
    done < <(find "$KNOWLEDGE_BASE_DIR" -name '*.md' -type f | sort)

    # Write index file
    cat > "$index_file" << EOF
---
title: "Knowledge Base Index"
category: index
tags: [index, toc]
owner: "system"
last_updated: "$now"
source: auto-generated
---

# Knowledge Base Index

<!-- Auto-generated by docs-query reindex / sync/index-rebuild.sh -->
<!-- Do not edit manually — regenerated on each sync -->

EOF

    # Output categories in a consistent order
    local ordered_categories=("architecture" "repos" "linear" "runbooks" "team")

    for cat in "${ordered_categories[@]}"; do
        if [ -n "${category_docs[$cat]:-}" ]; then
            local display_cat
            display_cat=$(echo "$cat" | sed 's/\b\(.\)/\u\1/g')
            echo "## ${display_cat}" >> "$index_file"
            echo "" >> "$index_file"
            echo "${category_docs[$cat]}" >> "$index_file"
            unset "category_docs[$cat]"
        fi
    done

    # Any remaining categories
    for cat in "${!category_docs[@]}"; do
        local display_cat
        display_cat=$(echo "$cat" | sed 's/\b\(.\)/\u\1/g')
        echo "## ${display_cat}" >> "$index_file"
        echo "" >> "$index_file"
        echo "${category_docs[$cat]}" >> "$index_file"
    done

    echo "Index rebuilt: $index_file"
}
